// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlsMU0mIrkz8196YovCncE5fmcmF2C_2k',
    appId: '1:233100004749:web:62f6fca55ba59964a901c4',
    messagingSenderId: '233100004749',
    projectId: 'silent-voice-e4f7f',
    authDomain: 'silent-voice-e4f7f.firebaseapp.com',
    storageBucket: 'silent-voice-e4f7f.appspot.com',
    measurementId: 'G-R657JPX8EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKsA8EkaTNy2kO0-kYCmub3PYwAVaDQ8',
    appId: '1:233100004749:android:6e7478099c31482ea901c4',
    messagingSenderId: '233100004749',
    projectId: 'silent-voice-e4f7f',
    storageBucket: 'silent-voice-e4f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEi_64xs-RKf-QhlbU6gy51ZeYyuzzUzY',
    appId: '1:233100004749:ios:ff54049357ccde7da901c4',
    messagingSenderId: '233100004749',
    projectId: 'silent-voice-e4f7f',
    storageBucket: 'silent-voice-e4f7f.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEi_64xs-RKf-QhlbU6gy51ZeYyuzzUzY',
    appId: '1:233100004749:ios:ff54049357ccde7da901c4',
    messagingSenderId: '233100004749',
    projectId: 'silent-voice-e4f7f',
    storageBucket: 'silent-voice-e4f7f.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
